# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFrame, QHeaderView, QLabel, QLineEdit,
    QListView, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_GUI(object):
    def setupUi(self, GUI):
        if not GUI.objectName():
            GUI.setObjectName(u"GUI")
        GUI.resize(1000, 807)
        self.centralwidget = QWidget(GUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.PauseButton = QPushButton(self.centralwidget)
        self.PauseButton.setObjectName(u"PauseButton")
        self.PauseButton.setGeometry(QRect(10, 40, 88, 27))
        self.StopButton = QPushButton(self.centralwidget)
        self.StopButton.setObjectName(u"StopButton")
        self.StopButton.setGeometry(QRect(10, 70, 88, 27))
        self.video_frame_1 = QFrame(self.centralwidget)
        self.video_frame_1.setObjectName(u"video_frame_1")
        self.video_frame_1.setGeometry(QRect(730, 40, 251, 171))
        self.video_frame_1.setFrameShape(QFrame.StyledPanel)
        self.video_frame_1.setFrameShadow(QFrame.Raised)
        self.video_frame_2 = QFrame(self.centralwidget)
        self.video_frame_2.setObjectName(u"video_frame_2")
        self.video_frame_2.setGeometry(QRect(730, 220, 251, 171))
        self.video_frame_2.setFrameShape(QFrame.StyledPanel)
        self.video_frame_2.setFrameShadow(QFrame.Raised)
        self.video_frame_3 = QFrame(self.centralwidget)
        self.video_frame_3.setObjectName(u"video_frame_3")
        self.video_frame_3.setGeometry(QRect(730, 400, 251, 171))
        self.video_frame_3.setFrameShape(QFrame.StyledPanel)
        self.video_frame_3.setFrameShadow(QFrame.Raised)
        self.video_label = QLabel(self.centralwidget)
        self.video_label.setObjectName(u"video_label")
        self.video_label.setGeometry(QRect(730, 10, 141, 19))
        self.verticalSlider = QSlider(self.centralwidget)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(30, 160, 16, 160))
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.verticalSlider_2 = QSlider(self.centralwidget)
        self.verticalSlider_2.setObjectName(u"verticalSlider_2")
        self.verticalSlider_2.setGeometry(QRect(80, 160, 16, 160))
        self.verticalSlider_2.setOrientation(Qt.Vertical)
        self.verticalSlider_3 = QSlider(self.centralwidget)
        self.verticalSlider_3.setObjectName(u"verticalSlider_3")
        self.verticalSlider_3.setGeometry(QRect(130, 160, 16, 160))
        self.verticalSlider_3.setOrientation(Qt.Vertical)
        self.verticalSlider_4 = QSlider(self.centralwidget)
        self.verticalSlider_4.setObjectName(u"verticalSlider_4")
        self.verticalSlider_4.setGeometry(QRect(180, 160, 16, 160))
        self.verticalSlider_4.setOrientation(Qt.Vertical)
        self.Actual_tool_pose_label = QLabel(self.centralwidget)
        self.Actual_tool_pose_label.setObjectName(u"Actual_tool_pose_label")
        self.Actual_tool_pose_label.setGeometry(QRect(120, 10, 111, 19))
        self.ManualCartButton = QPushButton(self.centralwidget)
        self.ManualCartButton.setObjectName(u"ManualCartButton")
        self.ManualCartButton.setGeometry(QRect(600, 30, 101, 27))
        self.ManualJointButton = QPushButton(self.centralwidget)
        self.ManualJointButton.setObjectName(u"ManualJointButton")
        self.ManualJointButton.setGeometry(QRect(600, 70, 101, 27))
        self.For_manual_label = QLabel(self.centralwidget)
        self.For_manual_label.setObjectName(u"For_manual_label")
        self.For_manual_label.setGeometry(QRect(10, 130, 91, 19))
        self.verticalSlider_5 = QSlider(self.centralwidget)
        self.verticalSlider_5.setObjectName(u"verticalSlider_5")
        self.verticalSlider_5.setGeometry(QRect(230, 160, 16, 160))
        self.verticalSlider_5.setOrientation(Qt.Vertical)
        self.verticalSlider_6 = QSlider(self.centralwidget)
        self.verticalSlider_6.setObjectName(u"verticalSlider_6")
        self.verticalSlider_6.setGeometry(QRect(280, 160, 16, 160))
        self.verticalSlider_6.setOrientation(Qt.Vertical)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(330, 200, 92, 23))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QRect(330, 160, 71, 25))
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setTabletTracking(True)
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setFrame(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(410, 160, 61, 25))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(480, 160, 61, 25))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(550, 160, 61, 25))
        self.lineEdit_4.setReadOnly(True)
        self.OnButton = QPushButton(self.centralwidget)
        self.OnButton.setObjectName(u"OnButton")
        self.OnButton.setGeometry(QRect(10, 10, 88, 27))
        self.OnButton_Gripper = QPushButton(self.centralwidget)
        self.OnButton_Gripper.setObjectName(u"OnButton_Gripper")
        self.OnButton_Gripper.setGeometry(QRect(330, 280, 88, 27))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(330, 260, 67, 17))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(500, 260, 121, 17))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 350, 171, 17))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(500, 280, 121, 25))
        self.listView_2 = QListView(self.centralwidget)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(10, 660, 681, 91))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 630, 171, 17))
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QRect(740, 620, 91, 25))
        self.lineEdit_5.setMouseTracking(True)
        self.lineEdit_5.setTabletTracking(True)
        self.lineEdit_5.setAcceptDrops(True)
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QRect(740, 650, 91, 25))
        self.lineEdit_6.setMouseTracking(True)
        self.lineEdit_6.setTabletTracking(True)
        self.lineEdit_6.setAcceptDrops(True)
        self.lineEdit_6.setFrame(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_7 = QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setGeometry(QRect(740, 680, 91, 25))
        self.lineEdit_7.setMouseTracking(True)
        self.lineEdit_7.setTabletTracking(True)
        self.lineEdit_7.setAcceptDrops(True)
        self.lineEdit_7.setFrame(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_8 = QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setGeometry(QRect(740, 710, 91, 25))
        self.lineEdit_8.setMouseTracking(True)
        self.lineEdit_8.setTabletTracking(True)
        self.lineEdit_8.setAcceptDrops(True)
        self.lineEdit_8.setFrame(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_9 = QLineEdit(self.centralwidget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setGeometry(QRect(870, 620, 101, 25))
        self.lineEdit_9.setMouseTracking(True)
        self.lineEdit_9.setTabletTracking(True)
        self.lineEdit_9.setAcceptDrops(True)
        self.lineEdit_9.setFrame(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_10 = QLineEdit(self.centralwidget)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setEnabled(True)
        self.lineEdit_10.setGeometry(QRect(870, 650, 101, 25))
        self.lineEdit_10.setMouseTracking(True)
        self.lineEdit_10.setTabletTracking(True)
        self.lineEdit_10.setAcceptDrops(True)
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_11 = QLineEdit(self.centralwidget)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setEnabled(True)
        self.lineEdit_11.setGeometry(QRect(870, 680, 101, 25))
        self.lineEdit_11.setMouseTracking(True)
        self.lineEdit_11.setTabletTracking(True)
        self.lineEdit_11.setAcceptDrops(True)
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setReadOnly(True)
        self.checkBox_2 = QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(740, 740, 211, 23))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(740, 600, 171, 17))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(870, 597, 171, 20))
        self.tableWidget = QTableWidget(self.centralwidget)
        if (self.tableWidget.columnCount() < 6):
            self.tableWidget.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        if (self.tableWidget.rowCount() < 4):
            self.tableWidget.setRowCount(4)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem9)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 370, 681, 151))
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget_2 = QTableWidget(self.centralwidget)
        if (self.tableWidget_2.columnCount() < 4):
            self.tableWidget_2.setColumnCount(4)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem13)
        if (self.tableWidget_2.rowCount() < 1):
            self.tableWidget_2.setRowCount(1)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, __qtablewidgetitem14)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(130, 40, 441, 51))
        self.tableWidget_2.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableWidget_4 = QTableWidget(self.centralwidget)
        if (self.tableWidget_4.columnCount() < 4):
            self.tableWidget_4.setColumnCount(4)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, __qtablewidgetitem18)
        if (self.tableWidget_4.rowCount() < 1):
            self.tableWidget_4.setRowCount(1)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, __qtablewidgetitem19)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setGeometry(QRect(10, 560, 441, 51))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 540, 171, 17))
        self.OnButton_Gripper_2 = QPushButton(self.centralwidget)
        self.OnButton_Gripper_2.setObjectName(u"OnButton_Gripper_2")
        self.OnButton_Gripper_2.setGeometry(QRect(460, 580, 88, 27))
        GUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(GUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 22))
        GUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(GUI)
        self.statusbar.setObjectName(u"statusbar")
        GUI.setStatusBar(self.statusbar)

        self.retranslateUi(GUI)

        QMetaObject.connectSlotsByName(GUI)
    # setupUi

    def retranslateUi(self, GUI):
        GUI.setWindowTitle(QCoreApplication.translate("GUI", u"MainWindow", None))
        self.PauseButton.setText(QCoreApplication.translate("GUI", u"Pause", None))
        self.StopButton.setText(QCoreApplication.translate("GUI", u"Stop", None))
        self.video_label.setText(QCoreApplication.translate("GUI", u"\u0412\u0438\u0434\u0435\u043e \u0441 \u043a\u0430\u043c\u0435\u0440", None))
        self.Actual_tool_pose_label.setText(QCoreApplication.translate("GUI", u"Actual tool pose", None))
        self.ManualCartButton.setText(QCoreApplication.translate("GUI", u"Manual Cart", None))
        self.ManualJointButton.setText(QCoreApplication.translate("GUI", u"Manual Joint", None))
        self.For_manual_label.setText(QCoreApplication.translate("GUI", u"For Manual", None))
        self.checkBox.setText(QCoreApplication.translate("GUI", u"\u0426\u0438\u043a\u043b", None))
        self.lineEdit.setText(QCoreApplication.translate("GUI", u"Stopped", None))
        self.lineEdit_2.setText(QCoreApplication.translate("GUI", u"Work", None))
        self.lineEdit_3.setText(QCoreApplication.translate("GUI", u"Off", None))
        self.lineEdit_4.setText(QCoreApplication.translate("GUI", u"Wait", None))
        self.OnButton.setText(QCoreApplication.translate("GUI", u"On", None))
        self.OnButton_Gripper.setText(QCoreApplication.translate("GUI", u"On", None))
        self.label.setText(QCoreApplication.translate("GUI", u"Gripper", None))
        self.label_2.setText(QCoreApplication.translate("GUI", u"\u0421\u0442\u0438\u043b\u044c \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f", None))
        self.label_3.setText(QCoreApplication.translate("GUI", u"\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u043c\u043e\u0442\u043e\u0440\u043e\u0432", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("GUI", u"Move_L", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("GUI", u"Move_J", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("GUI", u"Move_C", None))

        self.label_4.setText(QCoreApplication.translate("GUI", u"\u041b\u043e\u0433\u0438", None))
        self.lineEdit_5.setText(QCoreApplication.translate("GUI", u"\u041a\u0440\u0430\u0441\u043d\u044b\u0439", None))
        self.lineEdit_6.setText(QCoreApplication.translate("GUI", u"\u0416\u0451\u043b\u0442\u044b\u0439", None))
        self.lineEdit_7.setText(QCoreApplication.translate("GUI", u"\u0417\u0435\u043b\u0451\u043d\u044b\u0439", None))
        self.lineEdit_8.setText(QCoreApplication.translate("GUI", u"\u0421\u0438\u043d\u0438\u0439", None))
        self.lineEdit_9.setText(QCoreApplication.translate("GUI", u"\u041a\u0440\u0443\u0433", None))
        self.lineEdit_10.setText(QCoreApplication.translate("GUI", u"\u041a\u0432\u0430\u0434\u0440\u0430\u0442", None))
        self.lineEdit_11.setText(QCoreApplication.translate("GUI", u"\u0422\u0440\u0435\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a", None))
        self.checkBox_2.setText(QCoreApplication.translate("GUI", u"\u0421\u0447\u0438\u0442\u044b\u0432\u0430\u043d\u0438\u0435 \u0448\u0442\u0440\u0438\u0445-\u043a\u043e\u0434\u043e\u0432", None))
        self.label_5.setText(QCoreApplication.translate("GUI", u"\u0426\u0432\u0435\u0442", None))
        self.label_6.setText(QCoreApplication.translate("GUI", u"\u0424\u043e\u0440\u043c\u0430", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("GUI", u"1", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("GUI", u"2", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("GUI", u"3", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("GUI", u"4", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("GUI", u"5", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("GUI", u"6", None));
        ___qtablewidgetitem6 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("GUI", u"\u0442\u0438\u043a\u0438", None));
        ___qtablewidgetitem7 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("GUI", u"\u0440\u0430\u0434\u0438\u0430\u043d\u044b", None));
        ___qtablewidgetitem8 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("GUI", u"\u0433\u0440\u0430\u0434\u0443\u0441\u044b", None));
        ___qtablewidgetitem9 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("GUI", u"\u0442\u0435\u043c-\u0440\u0430", None));
        ___qtablewidgetitem10 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("GUI", u"x", None));
        ___qtablewidgetitem11 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("GUI", u"y", None));
        ___qtablewidgetitem12 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("GUI", u"z", None));
        ___qtablewidgetitem13 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("GUI", u"gripper", None));
        ___qtablewidgetitem14 = self.tableWidget_2.verticalHeaderItem(0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("GUI", u"pose", None));
        ___qtablewidgetitem15 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("GUI", u"x", None));
        ___qtablewidgetitem16 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("GUI", u"y", None));
        ___qtablewidgetitem17 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("GUI", u"z", None));
        ___qtablewidgetitem18 = self.tableWidget_4.horizontalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("GUI", u"gripper", None));
        ___qtablewidgetitem19 = self.tableWidget_4.verticalHeaderItem(0)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("GUI", u"pose", None));
        self.label_7.setText(QCoreApplication.translate("GUI", u"\u0417\u0430\u0434\u0430\u0442\u044c \u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b", None))
        self.OnButton_Gripper_2.setText(QCoreApplication.translate("GUI", u"\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c", None))
    # retranslateUi

